[package]
name = "crypto-trading-strategy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
crypto-trading-config = { path = "../config" }
crypto-trading-domain = { path = "../domain" }
rust_decimal.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
